spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_drive?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672

# MinIO对象存储配置
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin

# Elasticsearch配置
elasticsearch:
  host: localhost
  port: 9200

# 日志配置
logging:
  level:
    com.clouddrive: debug

# 服务器配置
server:
  port: 8080 