spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_drive?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  # Redis配置
  data:
    redis:
      host: redis
      port: 6379
  # RabbitMQ配置
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

# MinIO对象存储配置
minio:
  endpoint: http://minio:9000
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}

# Elasticsearch配置
elasticsearch:
  host: elasticsearch
  port: 9200

# 日志配置
logging:
  level:
    com.clouddrive: info
  file:
    name: /var/logs/cloud-drive/application.log

# 服务器配置
server:
  port: 8080 